title       = "pplx"
baseURL     = "https://perplexity-cli.tamnd.com/"
description = "Query Perplexity AI from the command line."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/perplexity-cli"
